language: r
warnings_are_errors: true
sudo: false
#- os: linux
- os: osx
cache: packages
before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update          ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install thrift; fi
#  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update          ; fi
#  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install graphviz; fi