language: r
r:
- oldrel
- release
- devel
warnings_are_errors: true
sudo: required
dist: bionic
before_install:
  - sudo apt install libboost-all-dev -y
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt update
  - sudo apt install docker-ce -y
  - cd /home/travis/build
  - wget --continue http://apache.claz.org/thrift/0.11.0/thrift-0.11.0.tar.gz
  - tar xf thrift-0.11.0.tar.gz
  - cd thrift-0.11.0
  - CFLAGS="-fPIC" CXXFLAGS="-fPIC" ./configure --without-java --without-lua --without-python --without-php --without-ruby --without-qt4 --without-qt5 --without-erlang --without-go --without-nodejs --without-py3
  - make
  - sudo make install
  - sudo ldconfig
  - docker pull omnisci/core-os-cpu:latest
  - docker run -d -p 6278:6278 -p 6274:6274 --name=omnisci omnisci/core-os-cpu:latest
  - cd /home/travis/build/omnisci/ROmniSci