language: r
warnings_are_errors: true
sudo: true
os: linux
cache: packages
before_install:
  - docker pull omnisci/core-os-cpu:latest
  - docker run -d --ipc=host -p 6278:6278 -p 6274:6274 --name=omnisci omnisci/core-os-cpu:latest
  - docker ps -a
  - wget --continue http://apache.claz.org/thrift/0.11.0/thrift-0.11.0.tar.gz
  - tar xvf thrift-0.11.0.tar.gz
  - cd thrift-0.11.0
  - CFLAGS="-fPIC" CXXFLAGS="-fPIC" ./configure --with-lua=no --with-python=no --with-php=no --with-ruby=no -with-qt4=no --with-qt5=no
  - make
  - make install