language: r
warnings_are_errors: true
sudo: required
os: linux
before_install:
  - docker pull omnisci/core-os-cpu:latest
  - docker run -d --ipc=host -p 6278:6278 -p 6274:6274 --privileged --name=omnisci omnisci/core-os-cpu:latest
  - docker ps -a
  - sudo apt install libboost-all-dev -qq
  - cd /home/travis/build
  - wget --continue http://apache.claz.org/thrift/0.11.0/thrift-0.11.0.tar.gz
  - tar xf thrift-0.11.0.tar.gz
  - cd thrift-0.11.0
  - CFLAGS="-fPIC" CXXFLAGS="-fPIC" ./configure --without-java --without-lua --without-python --without-php --without-ruby --without-qt4 --without-qt5 --without-erlang --without-go --without-nodejs --without-py3
  - make -s
  - sudo make install -s
  - sudo ldconfig
  - cd /home/travis/build/omnisci/ROmniSci