// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// connect_binary
SEXP connect_binary(const std::string& host, int& port, const std::string& user_name, const std::string& passwd, const std::string& db_name);
RcppExport SEXP _ROmniSci_connect_binary(SEXP hostSEXP, SEXP portSEXP, SEXP user_nameSEXP, SEXP passwdSEXP, SEXP db_nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type host(hostSEXP);
    Rcpp::traits::input_parameter< int& >::type port(portSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type user_name(user_nameSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type passwd(passwdSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type db_name(db_nameSEXP);
    rcpp_result_gen = Rcpp::wrap(connect_binary(host, port, user_name, passwd, db_name));
    return rcpp_result_gen;
END_RCPP
}
// get_table_details
List get_table_details(SEXP conn, std::string table_name);
RcppExport SEXP _ROmniSci_get_table_details(SEXP connSEXP, SEXP table_nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type conn(connSEXP);
    Rcpp::traits::input_parameter< std::string >::type table_name(table_nameSEXP);
    rcpp_result_gen = Rcpp::wrap(get_table_details(conn, table_name));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ROmniSci_connect_binary", (DL_FUNC) &_ROmniSci_connect_binary, 5},
    {"_ROmniSci_get_table_details", (DL_FUNC) &_ROmniSci_get_table_details, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_ROmniSci(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
