# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' connect
#'
#'
#' @export
connect <- function(host, port, user_name, passwd, db_name) {
    .Call('_ROmniSci_connect', PACKAGE = 'ROmniSci', host, port, user_name, passwd, db_name)
}

#' disconnect
#'
#'
#' @export
disconnect <- function(conn) {
    invisible(.Call('_ROmniSci_disconnect', PACKAGE = 'ROmniSci', conn))
}

#' get_table_details
#'
#'
#' @export
get_table_details <- function(conn, table_name) {
    .Call('_ROmniSci_get_table_details', PACKAGE = 'ROmniSci', conn, table_name)
}

